version: 0.0
os: linux

files:
   - source: /
     destination: /var/www/html
permissions:
   - object: /var/www/html
     pattern: "**"
     owner: ubuntu
     group: www-data
     mode: 775
     type:
       - directory
   - object: /var/www/html
     pattern: "**"
     owner: ubuntu
     group: www-data
     mode: 664
     type:
       - file

